---
- name: Check if K3s uninstall script exists
  stat:
    path: "{{ k3s_uninstall_path }}"
  register: k3s_uninstall

- name: Uninstall K3s
  ansible.builtin.shell: >-
    {{ k3s_uninstall_path }} >> ~/k3s_uninstall_log.txt
  when: k3s_uninstall.stat.exists
