---
- name: Install K3s on nodes (worker)
  ansible.builtin.shell: >-
    INSTALL_K3S_VERSION="{{ k3s_version | default('') }}"
    INSTALL_K3S_EXEC="{{ extra_agent_args | default('') }}"
    K3S_URL="https://{{ groups['master'][0] }}:6443"
    K3S_TOKEN="{{ hostvars[groups['master'][0]]['node_token'] }}"
    ~/k3s_install.sh >> ~/k3s_install_log.txt
  args:
    chdir: "~"
    creates: /var/lib/rancher/k3s/agent/kubelet.kubeconfig
